### ISSUE TITLE
Attributes without value disappear

### ISSUE THREAD

**Issue by zeppelin** [emberjs/ember.js#10169]
With ember-canary

```html
<form novalidate></form>
```
is rendered as:

```html
<form></form>
```

1.9.1 renders the element correctly

JSBin: http://emberjs.jsbin.com/diveni/1/edit?html,output

**Comment by rwjblue** [comment]
This should be fixed on master and in beta (both are using v0.8.1 of htmlbars).

**Comment by wagenet** [comment]
I'm still seeing issues with this. I'm on ember-cli 0.1.5 with ember 1.10.beta.4 with ember-cli-htmlbars 0.6.0.

**Comment by wagenet** [comment]
See http://emberjs.jsbin.com/duxomaqiho/1/edit?html,js,output

**Comment by rwjblue** [comment]
@wagenet - Yours is not the same as the originally reported issue.  This issue is with plain HTML in a template `<form novalidate></form>`.  You are using `attributeBindings` which is quite different.

A screenshot from the original JSBin (demonstrating that this is working properly now):

![screenshot](http://monosnap.com/image/L5ikxqFlU3WGEHmldM7oxepm1cahRn.png)

**Comment by rwjblue** [comment]
@wagenet - Closing this in favor of https://github.com/emberjs/ember.js/issues/10202 (which is specifically for the issue in your JSBin).

**Comment by wagenet** [comment]
@rwjblue you're right. My mistake.
