### ISSUE TITLE
Ember Helpers

### ISSUE THREAD

**Issue by btecu** [emberjs/ember.js#10333]
Using *canary* to be able to use HTMLBars bounds...

I've updated to a more recent canary version and everything stopped working.

`Uncaught TypeError: undefined is not a function`
Caused by Helpers.js @17:
`Ember.Handlebars.helper('singularize', singularize);`

Then the following is thrown:
`Error while processing route: element undefined is not a function TypeError: undefined is not a function
    at exports.default.Ember.default.Route.extend.model (http://localhost:4200/assets/mynew-cli.js:505:31)
    at EmberObject.default.extend.deserialize (http://localhost:4200/assets/vendor.js:35109:19)
    at applyHook (http://localhost:4200/assets/vendor.js:59718:32)
    at Object.HandlerInfo.runSharedModelHook (http://localhost:4200/assets/vendor.js:57728:22)
    at Object.subclass.getModel (http://localhost:4200/assets/vendor.js:57954:21)
    at __exports__.bind (http://localhost:4200/assets/vendor.js:59587:19)
    at tryCatch (http://localhost:4200/assets/vendor.js:60044:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:60056:17)
    at publish (http://localhost:4200/assets/vendor.js:60027:11)
    at http://localhost:4200/assets/vendor.js:39614:7`

Using Ember-cli 0.1.12.

**Comment by rwjblue** [comment]
Can you repro the error in a JSBin?  Here is the base one I usually use for demoing new issues against canary: http://emberjs.jsbin.com/rwjblue/248/edit?html,js,output.

**Comment by mitchlloyd** [comment]
I just downloaded this Canary and have the same error. I'll see if I can reproduce.

**Comment by rwjblue** [comment]
Took another shot at replication with canary, and my stupid simple helper seems to work properly. Definitely need help reproducing.

My stupid helper: http://emberjs.jsbin.com/rwjblue/272/edit

**Comment by mitchlloyd** [comment]
The error is coming from ember-inflector. Here is the relevant commit:

https://github.com/stefanpenner/ember-inflector/commit/fb6093f5a6fb4c139e8228cf7da328dfa6bd6161

It looks like @btecu and I have a library using ember-inflector that needs to be updated.

**Comment by mitchlloyd** [comment]
Seems to be Ember Data which is set at 1.2.0.

**Comment by rwjblue** [comment]
https://github.com/stefanpenner/ember-inflector/issues/63

**Comment by mitchlloyd** [comment]
For what it's worth, changing to the latest Canary from yesterday fixed my issue for now:

4b633e2326b14fd7e069be369ce5b6069ed8ac22

**Comment by btecu** [comment]
Yes, I think it happens during serialization (using Ember Data 1.0.0.beta-14.1).

How do you specify the canary version in bower?

**Comment by mitchlloyd** [comment]
In dependencies:

    "ember": "components/ember#025083b0abef95fd7372c979cc07f0363064da57",

The gotcha is to make sure you use the SHA from http://github.com/components/ember canary branch and not from the actual Ember repository.

**Comment by rwjblue** [comment]
@mitchlloyd - I do not think I understand the underlying problem yet, have you been able to reproduce in a JSBin?

Here is one using canary of ember-data and ember, that can use `{{singularize}}` just fine: http://emberjs.jsbin.com/qovara/3/edit...

**Comment by mitchlloyd** [comment]
I narrowed it down to this commit:

https://github.com/emberjs/ember.js/commits/1905161aaa8dcd5fb35fc1367dc0c5f13e96e9e3

Is it possible that there is something going on here that could result in `Ember.Handlebars.helper` being undefined?

**Comment by rwjblue** [comment]
[This JSBin](http://emberjs.jsbin.com/rwjblue/272/edit?html,css,js,output) uses `Ember.Handlebars.helper` without issue on latest canary builds, but ember-inflector is using `Ember.HTMLBars.helper`. As detailed in https://github.com/stefanpenner/ember-inflector/issues/63 the ember-inflector should not be using `Ember.HTMLBars.helper` as [it is currently](https://github.com/stefanpenner/ember-inflector/blob/994c9a2a1759925286afbd2d16b2c50602223f35/packages/ember-inflector/lib/helpers.js#L18-L20).

**Comment by mitchlloyd** [comment]
Starting a new ember-cli project, and upgrading to latest Canary Ember and latest Ember Data beta (https://github.com/mitchlloyd/ember-issue-test) demonstrates the problem. If you load the index page you should see the errors that we're seeing.

https://github.com/mitchlloyd/ember-issue-test

**Comment by rwjblue** [comment]
@mitchlloyd - Thanks for the repro, thats exactly what I needed.  I'm working on it now...

**Comment by rwjblue** [comment]
I believe that https://github.com/ember-cli/ember-cli/issues/3177 is due to the same root cause.

**Comment by btecu** [comment]
Thanks @rwjblue and @mitchlloyd.

**Comment by rwjblue** [comment]
Fixed by https://github.com/thomasboyt/defeatureify/pull/13.  Please update to the latest build.

@mitchlloyd - I updated your demo repo, and submitted a PR https://github.com/mitchlloyd/ember-issue-test/pull/1.

**Comment by johanobergman** [comment]
I am still getting this error on the latest Ember 1.11 beta. Works on canary though.

**Comment by al3x-edge** [comment]
I'm also getting the same behavior as @johanobergman.

**Comment by rwjblue** [comment]
@johanobergman / @al3x-edge : Can y'all open up a new issue with a repro?  The cause of this particular issue is definitely fixed, but perhaps there are other issues to be tracked down...

**Comment by johanobergman** [comment]
I've opened a new issue here: #10403.
