### ISSUE TITLE
Input helper type="email" breaks IE9

### ISSUE THREAD

**Issue by ctruelson** [emberjs/ember.js#10860]
IE9 throws "Invalid argument" for input helpers with a `type` of `email`

Ember 1.11.1

**Comment by justinwoo** [comment]
IE9 does not support `input.type` of `email`

see: http://www.quirksmode.org/html5/inputs/

**Comment by ctruelson** [comment]
Yes but I don't believe this broke or threw an error until ember 1.11

**Comment by SaladFork** [comment]
This is true for all new HTML5 input types. In previous versions it degraded gracefully to a text-type input. This is also true if you use `<input>`. However, using the `{{input}}` helper causes it to fail in IE9.

**Comment by awaer** [comment]
Looks like this is fixed as a part of #10458 with PR #10690.

**Comment by rwjblue** [comment]
Should be fixed now.

**Comment by adambuczynski** [comment]
This is still throwing an error for input type "tel" or "number" in IE9 it seems for Ember 1.11.3. Was this fixed in the 1.11.x branch? We are stuck with 1.11 and require IE9 support, so it would be nice to get this working.
