### ISSUE TITLE
Ember.computed.sort fails on 2.x with null list (worked in 1.13)

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#12207]
When the target of `Ember.computed.sort` is null it causes a crash on the 2.x branch. It worked on the Ember 1.13.x branch.

Ember 1.13.9: http://emberjs.jsbin.com/mejidiniju/1/edit
Ember 2.1-beta.2: http://emberjs.jsbin.com/pujaxeceqe/1/edit

**Comment by stefanpenner** [comment]
Should be fixed on master

**Comment by fivetanley** [comment]
@stefanpenner still present on master http://emberjs.jsbin.com/pucelamoce/1/edit?html,css,js,output

**Comment by workmanw** [comment]
@stefanpenner @fivetanley Seems like the easiest solution is to check `items` for null and bail early here: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L573

I can submit a pull if you think that's the way to go. I'm not really up on Ember's style guide anymore :(

**Comment by rwjblue** [comment]
We did a similar fix to `Ember.computed.sum` in https://github.com/emberjs/ember.js/pull/12170.  Seems like we need to add a similar guard to `Ember.computed.sort`.

@workmanw - Can you take a look at the PR above, and submit a PR?

**Comment by stefanpenner** [comment]
Ah sort not map

**Comment by workmanw** [comment]
@rwjblue @stefanpenner Yea, I'll make it so.
