### ISSUE TITLE
Performance degradation modifying component attributes

### ISSUE THREAD

**Issue by Emrvb** [emberjs/ember.js#12833]
I've recently started migrating several pre-glimmer applications to Ember 2.2. I've noticed a severe performance degradation when updating attributes on components.

I'm not sure this is actually a bug. If not, the guides must be updated explaining what kind of data you should pass to components and what the possible consequences are when you change that data.

I've created this twiddle https://ember-twiddle.com/e2a40a26ddeb53106778 to demonstrate the issue. In this twiddle I pass data around a lot of components. When capturing a timeline of the application while changing that data, I see an awful lot of htmlbars (revalidation) stuff going on. Compared to 12.1 the cost of simply changing an attribute that might not even be bound to the dom is enormous. 

Data passed and observed behavior:

x: Passed to all components, rendered by only one.
Change seems to revalidate all nodes.

y: Passed to all components, rendered by none.
Change seems to revalidate all nodes.

z: Local to components, rendered and updated by only one.
Change seems to revalidate the entire node tree leading to the component that renders z.

data: Passed to all components.

data.x: Rendered by only one component.
Change seems to revalidate the entire node tree leading to the component that renders data.x.

data.y: Not rendered by any component.
Change does not cause any revalidation, as expected.

**Comment by stefanpenner** [comment]
Are your tests using ember prod? We fixed some issues with dev debug assertions that unfortunately slow down dev builds. I would like to be sure you are not just noticing that.

**Comment by Emrvb** [comment]
I just did a production build with Ember 2.3.0. I still see a lot of htmlbars activity. There seem to be a few differences between the debug and production build timelines but they're marginal.

**Comment by stefanpenner** [comment]
Ok thank you for checking. I believe we have a related example that demonstrates this. And it is something we are continuing effort on.

**Comment by johnnyshields** [comment]
Is there a status update on this or a linked issue?

**Comment by stefanpenner** [comment]
cc @chancancode / @wycats you current work is related to this, so you guys should take a look.

**Comment by pixelhandler** [comment]
@Emrvb @johnnyshields @stefanpenner is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
