### ISSUE TITLE
view._renderNode.lastResult giving "Uncaught TypeError: Cannot read property 'lastResult' of null"

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#13968]
I have unsuccessful in tracking this down so far. A few days ago when canary ticked over to beta, I noticed that canary the whole time and now beta are failing for my addon:
```
Uncaught TypeError: Cannot read property 'lastResult' of null
Renderer_revalidateTopLevelView @ ember.debug.js:14397
exports.default._emberMetalMixin.Mixin.create._Mixin$create.revalidate @ ember.debug.js:42831
invoke @ ember.debug.js:990
flush @ ember.debug.js:1054
flush @ ember.debug.js:862
end @ ember.debug.js:176
(anonymous function) @ ember.debug.js:742
```

Here is one of the travis build logs https://travis-ci.org/kellyselden/ember-tree/builds/148237768. I tried removing dependencies to narrow it down, but then tests start failing for other reasons.

When debugging, `if (view._renderNode.lastResult) {` passes through the first time, then fails on the second. I inspected `view` and although it doesn't have a `_renderNode` property, it does have a `lastResult` property. I don't know if that helps.

**Comment by krisselden** [comment]
_renderNode is private and not part of glimmer2

**Comment by kellyselden** [comment]
OK, but I don't know how I'm causing this failure. I'm not using any private code in my addon code, maybe one of the addons I'm using is having issues with glimmer 2. My ember debugging skills are apparently lacking in this case.

**Comment by kellyselden** [comment]
This is still happening. Would you say it's probably an addon I'm using that's using an old htmlbars version? Any debugging tips are appreciated! cc @krisselden

**Comment by rwjblue** [comment]
It should be fixed by https://github.com/emberjs/ember.js/pull/14110.

**Comment by kellyselden** [comment]
@rwjblue Using that branch, it didn't seem to fix it: https://travis-ci.org/kellyselden/ember-tree/jobs/154205905

**Comment by rwjblue** [comment]
@kellyselden - Sorry, I forgot to update the bower tree after my last commit. Can you blow cache and test again?

**Comment by kellyselden** [comment]
@rwjblue Works now!
