### ISSUE TITLE
[Glimmer 2] Method toString in a helper's hash does not exists

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/ember.js#14489]
Assume the following helper exists:

``` js
//app/helper/my-helper.js

export function myHelper(params, hash) {
  console.log('calling toString in params', params.toString());
  console.log('calling toString in hash', hash.toString());
  return params;
}
```

When calling the `toString()` in the `hash`, we get an undefined for `toString()` in a `EmptyObject`. 

This used to work in v2.8.

Reproduction: https://ember-twiddle.com/6ece3db737132676ecceb87dbf07e770?openFiles=helpers.my-helper.js%2C

**Comment by josemarluedke** [comment]
I think the related code is this: https://github.com/tildeio/glimmer/blob/master/packages/glimmer-util/lib/collections.ts#L13-L24

I'm happy to get a PR if someone can give some assistance on the fix.

**Comment by rwjblue** [comment]
Not sure this is something we should fix.  As you noted the hash object is created by with a null prototype,  this allows you to check to see what has keys were provided without having to use hasOwnProperty checks throughout your helpers.

**Comment by Serabe** [comment]
Completely agree on this not being a bug. We can keep this open to improve documentation, though.

**Comment by bradleypriest** [comment]
Here's how we fixed this exact thing for ember-cli-accounting. 
https://github.com/cibernox/ember-cli-accounting/pull/21

**Comment by rwjblue** [comment]
Whoops, forgot we were keeping it open for someone to add some info to the docs.

**Comment by sukima** [comment]
Why not make `(hash)` use a `Map` instead, that why you could still iterate over the keys (`myMap.keys()`) or lookup keys (`myMap.has('prop')`) and still have a `toSting()`?
