### ISSUE TITLE
Application crashes when uses whitespace control

### ISSUE THREAD

**Issue by sergiferran** [emberjs/ember.js#14993]
Hi,
I've found an issue when using whitespace control in templates, only happens when using a Helper inside the block and you change the value:
```
{{#each values as |value index|~}}
  {{highlight-text value=value highlight='a'}}
{{~/each}}
```
^ Here will break ^
```
{{#each values as |value index|}}
  {{value}}
{{/each}}
```
^ Here won't break ^
here is the example: [ember-twiddle](https://ember-twiddle.com/9b46de7b2f4e387e7d710948019d0912?openFiles=templates.application.hbs%2C)

To reproduce: remove any whole line or add a new line in the textarea, open the console and you'll get:
```
Uncaught TypeError: Cannot read property 'nextSibling' of null
    at DOMChanges.insertAfter (ember.debug.js:50529)
    at ListBlockOpcode.evaluate (ember.debug.js:54400)
    at UpdatingVM.execute (ember.debug.js:54155)
    at RenderResult.rerender (ember.debug.js:54094)
    at RootState._this.render (ember.debug.js:11854)
    at runInTransaction (ember.debug.js:23035)
    at InteractiveRenderer._renderRoots (ember.debug.js:12115)
    at InteractiveRenderer._renderRootsTransaction (ember.debug.js:12153)
    at InteractiveRenderer._revalidate (ember.debug.js:12192)
    at invoke (ember.debug.js:336)
```

But if you remove the whitespace control in the `each` helper, then no breaks at all.

**Comment by CvX** [comment]
Ember-twiddle example seems to work now. Has this issue been fixed?

**Comment by sergiferran** [comment]
It still breaks, just remove one by one the last characters until you remove one line, then in inspector, you'll have the error

**Comment by CvX** [comment]
It seems that this issue has been fixed in Ember 3.4.3 (ie. the problem is reproducible in every version up to 3.4.2, and doesn't occur anymore in 3.4.3-3.4.6).

**Comment by sergiferran** [comment]
Yeah, definitely it doesn't crash with `3.4.3` version

**Comment by bajajneha27** [comment]
@sergiferran Are you talking about ember-cli version?

I've ember-cli 3.8.1 and ember "3.0.0-beta.2" . I still face this issue.

**Comment by sergiferran** [comment]
> @sergiferran Are you talking about ember-cli version?
> 
> I've ember-cli 3.8.1 and ember "3.0.0-beta.2" . I still face this issue.

@bajajneha27 i think we are talking about ember-source rather than ember-cli.

**Comment by bajajneha27** [comment]
> > @sergiferran Are you talking about ember-cli version?
> > I've ember-cli 3.8.1 and ember "3.0.0-beta.2" . I still face this issue.
> 
> @bajajneha27 i think we are talking about ember-source rather than ember-cli.

Okay. I do have ember-source 3.8.0 and I still get this issue. Have googled around but now I'm stuck on how to fix this.

**Comment by sdhull** [comment]
We're on Ember 3.5.0 and still getting a ton of these in Rollbar, mostly from one user on Chrome on Windows. The telemetry data is useless, as is the backtrace:

```
File 0 line 29762 col 56 in r.insertAfter
File 0 line 31553 col 21 in i.evaluate
File 0 line 31322 col 24 in e.execute
File 0 line 31627 col 16 in e.rerender
File 0 line 40294 col 35 in e.l.render
File 0 line 45000 col 20 in C
File 0 line 40575 col 78 in t.e._renderRoots
File 0 line 40608 col 22 in t.e._renderRootsTransaction
File 0 line 40651 col 18 in t.e._revalidate
File 0 line 33798 col 28 in e.invokeWithOnError
```

I wonder if some browser setting causes this in some circumstances?

**Comment by pajamaw** [comment]
@bajajneha27 &  @sdhull 
If you guys are still seeing the issue. My workaround for this in my ember 3.1 app was changing 
```                      
{{#each options as |option|}}
    <option value={{option.id}}>{{option.title}}</option>
 {{/each}}
```
to this 
```
  {{#each options as |option|}}
      {{option option}}
  {{/each}}
```
and creating a helper where the logic occured
```export function option(params) {
  return `<option value='${params.id}'>${params.title}</option>`;
}```

Hope that helps!
