### ISSUE TITLE
Ember 2.14 - classCallCheck is not a function error while running tests in prod mode

### ISSUE THREAD

**Issue by mani-mishra** [emberjs/ember.js#15671]
This is probably similar to #15506.
We have a CI task for running all our tests in both dev and prod mode. 
We started this, when the app started failing in production, after an ember upgrade (everything was green in normal dev/tests mode).

So the same CI task is complaining of ```(0 , n.classCallCheck) is not a function)```.

Locally it can be reproduced by either running the tests on command line like,
```ember test --environment production``` 

```
TypeError: (0 , n.classCallCheck) is not a function
    at new a (http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:150:61)
    at Function.d (http://localhost:7357/assets/vendor-95589e23a28b7d0c0a9b34af4f24b7ff.js:3155:7)
    at o (http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:147:106)
    at http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:98:51
    at e.run (http://localhost:7357/assets/vendor-95589e23a28b7d0c0a9b34af4f24b7ff.js:1121:32)
    at Le (http://localhost:7357/assets/vendor-95589e23a28b7d0c0a9b34af4f24b7ff.js:1903:260)
    at a (http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:155:56)
    at a.helpers.(anonymous function).meta.wait.n (http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:98:20)
    at Object.<anonymous> (http://localhost:7357/assets/tests-d912cb57e87899b732daee3ea65cab72.js:498:101)
    at e (http://localhost:7357/assets/test-support-53bc5911338063adc4ccac6eb3b4dca0.js:277:288)
    at g.run (http://localhost:7357/assets/test-support-
....
```

or 

```ember test --server true --environment production``` 
and load chrome. One would see following,

<img width="1184" alt="ember2 14-tests-in-prod-mode" src="https://user-images.githubusercontent.com/3315240/30603459-2a2f7674-9d85-11e7-8c79-486890fa8111.png">

**Comment by mani-mishra** [comment]
Any updates on this :eyes: ? Our app is still at 2.13 because of this.

**Comment by vothaison** [comment]
On my environment, ember.prod.js works, only ember.debug.js produces the error. The version is 2.16.2 btw.

**Comment by rwjblue** [comment]
I believe this is fixed now. Tested with:

```
ember new foo
cd foo
ember g acceptance-test index
# edit test to pass properly
ember test --environment=production
```

**Comment by mani-mishra** [comment]
@rwjblue Can you please confirm the ember/ember-cli version you tested with?
I tested with 2.18.0, still seeing the same error.

I think we need to migrate our app to latest versions.

**Comment by rwjblue** [comment]
I tested with current release versions of both Ember and ember-cli (3.1). Also, I just did a rudimentary test, so it’s possible there is something specific needed to repro that we haven’t discovered to date. Happy to reopen if I’ve closed in error.
