### ISSUE TITLE
Deeply nested partials is broken in Ember 2.15.x onwards

### ISSUE THREAD

**Issue by kratiahuja** [emberjs/ember.js#15791]
# Problem

If an addon/app is invoking `partial` in a deeply nested manner (ie invoking a partial then invokes another partial) is currently broken. What really is broken is that the context of the template that first invokes a partial isn't being passed down to the n-th (n > 1) `partial` call. This is causing apps to break when upgrading to Ember 2.16.1.

If there is only one level of `partial` invocation, it will work since the template context is only passed down to the first level. 

# Example

Let's say a template (`app/templates/partials.hb`s) invokes a partial as follows:

```hbs
{{#each model as |record index|}}
  {{partial 'my-partials/some-partials}}
{{/each}}
```

Now the `my-partials/some-partials` will have the `record` correctly available in `some-partials`. However if `some-partials` is invoking another partial called `name`, then `record` is `undefined`

# Reproduction

https://github.com/kratiahuja/partials-broken

Run `ember s` and visit `https://localhost:4200/partials`. You will see the record name being `undefined`. Switching to `ember-source@2.14.x` renders the record name correctly.

cc: @rwjblue

**Comment by kratiahuja** [comment]
I know the deeply nested partials can be simplified into component invockation.

**Comment by kratiahuja** [comment]
Happy to help fix this if someone could help give me a direction. I believe the bug is in glimmer-vm right?

**Comment by atomkirk** [comment]
I can confirm this. In my case, 
```
{{#each model as |record index|}}
  {{partial 'my-partials/some-partials}}
{{/each}}
```
is in a partial and `record` is not available in `some-partials`

**Comment by thnima** [comment]
I have the same issue.
But it works again if I move the loop into the deeply nested partial like this:

Partial 1:
`{{partial 'my-partials/some-partials}}`

Some-Partials:
`{{#each model as |record index|}}
  {{partial 'my-partials/more-partials}}
{{/each}}`

**Comment by rwjblue** [comment]
Fixed by https://github.com/glimmerjs/glimmer-vm/pull/732 and https://github.com/emberjs/ember.js/pull/15797. Released in v2.16.2.

**Comment by atomkirk** [comment]
I'm using 2.16.2 and I'm still seeing it. Did you mean 2.16.3 maybe?

**Comment by rwjblue** [comment]
@atomkirk - Yes, lets treat it as a separate bug, would you mind filing (and possibly creating a failing test case like in https://github.com/emberjs/ember.js/pull/15797 and https://github.com/glimmerjs/glimmer-vm/pull/732)?
