### ISSUE TITLE
"You attempted to access the `_onLookup`" error in Engine

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#16610]
I have created a [demo app](https://github.com/amk221/-ember-engine-get-issue/commit/353c0fd44401218d4f7271fe051a562390474f60) with a simple use of `unknownProperty`.

Using `{{myService.myUnknownProperty}}` works in the parent app, but not in the Engine.

Instead, I get the recently added [error](
https://github.com/emberjs/ember.js/blob/eca00feb5b4d83a5bed2bf7924b839f58ff6e7cc/packages/ember-runtime/lib/system/core_object.js#L81) that informs the user about the changes regarding [`.get`](https://www.emberjs.com/blog/2018/04/13/ember-3-1-released.html#toc_es5-getters-for-computed-properties-2-of-4)

(Sorry if this is in the wrong repo, the error is coming from ember.js repo not the Engine repo so thought I'd raise here)

**Comment by rwjblue** [comment]
Thank you for reporting (and for the minimal reproduction)!

**Comment by wojm** [comment]
I had a similar bug. Was unable to solve it. I documented it here: https://discuss.emberjs.com/t/issues-upgrading-from-2-13-to-3-1/14695/5

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember.js/pull/16613

**Comment by toranb** [comment]
With ember v3.1 and engines v0.5.20 I'm still having this problem. Any chance this patch will male its way into 3.1x ?
