### ISSUE TITLE
sortyBy on Ember.Array no longer returns an Ember.Array

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#16861]
In Ember 3.2, this:

```js
Ember.A([{id: 1}]).sortBy('id').lastObject
```

returns `{id: 1}` because `sortBy` on an Ember array returns another Ember array, which implements `lastObject`.

But in Ember 3.3 it returns undefined, because `sortBy` returns a native array.

This broke ember-elsewhere so it's possible it broke other apps or addons. https://github.com/ef4/ember-elsewhere/issues/24

**Comment by rwjblue** [comment]
I think this should have been fixed by https://github.com/emberjs/ember.js/pull/16785, though I haven't dug in to confirm/deny...

**Comment by bekzod** [comment]
I can look at this tomorrow 😉

**Comment by ef4** [comment]
This is still broken in 3.4.0-beta.1, which already includes #16785 as far as I can tell.

**Comment by pixelhandler** [comment]
@ef4 sounds like a bug, perhaps next steps are to create a failing test? anyone up for that task?

**Comment by rwjblue** [comment]
I believe this is resolved, @ef4 can you confirm?

**Comment by lupestro** [comment]
I just ran into this porting our code from 2.18 to 3.4. Given the timing, would I expect the fix to appear in 3.5 or in canary? This seems important enough to backport, but then, since it was the only thing that broke on my project going to 3.4 (the next LTS in cycle), as my only gored ox, it would, right? :)

**Comment by rwjblue** [comment]
Since the change that I _thought_ fixed it (https://github.com/emberjs/ember.js/pull/16785) **should** already be in 3.4 and it is still broken in 3.4.6, I don't think we currently have a valid fix.

Someone needs to dig in to determine what exactly is going on. If we can get a fix done, we should absolutely backport to 3.4.

**Comment by choclaudio** [comment]
So, I did a fast investigation of it and @ember/-internals/runtime/lib/mixins/array.js implements the [sortBy] method. This method explicitly invokes [this.toArray()] that maps to and returns a native array.
I removed the [toArray] part and all test pass (including a test I did to check that sortBy returns an Ember array).

For the checking in the test I included and exposed the internal isEmberArray in the array test helper.
What I noticed there is something that potentially might be the source to other bugs.

I would expect that isEmberArray would return a boolean in all cases. It will only return a boolean if what is provided to isEmberArray is an EmberArray, otherwise it will return undefined. This seems like another bug to me.

Could somebody please verify my findings and help figure out what best to do?

**Comment by rwjblue** [comment]
> I would expect that isEmberArray would return a boolean in all cases. It will only return a boolean if what is provided to isEmberArray is an EmberArray, otherwise it will return undefined. This seems like another bug to me.

I don't think its necessarily a bug, but it seems fine to fix

**Comment by rwjblue** [comment]
> So, I did a fast investigation of it and @ember/-internals/runtime/lib/mixins/array.js implements the [sortBy] method. This method explicitly invokes [this.toArray()] that maps to and returns a native array.

Seems like `toArray` should be returning an `A()` (which would be a native array when prototype extensions are on, and an extended native array when they are not).

**Comment by choclaudio** [comment]
Ah, ok. Thanks @rwjblue, I was not aware that the abstraction over native arrays and Embers  extended native array was handled in A(). I will look into this during the coming days and hopefully create a valid PR.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? Since Ember.Array will eventually be removed, maybe this can be closed?

By closing some old issues we reduce the list of open issues to a more manageable set.
