### ISSUE TITLE
3.9.0-beta.1 doesn't work with ember-macro-helpers

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#17641]
This is a tracker issue as I don't know when I'll be able to dig in. @pzuraq is aware of the issue, as it is most likely related to the ComputedProperty changes.

https://travis-ci.org/kellyselden/ember-macro-helpers/builds/495361848

**Comment by rwjblue** [comment]
There are a few private APIs being used throughout ember-macro-helpers (e.g. usage of `_getter` / `_setter`) which are reasonable places to start poking, but we will definitely need more information to be able to work through whats going on...

**Comment by pzuraq** [comment]
`_getter` and `_setter` and other private APIs were removed, so that could definitely be causing this breakage. It may be possible to add them back in `ember-macro-helpers` own `computed` wrapper.

**Comment by rwjblue** [comment]
I believe this was fixed (we reverted the decorator refactors in 3.9, and in 3.10 we added back _getter to unblock ember-macro-helpers).

Closing...

**Comment by bendemboski** [comment]
@rwjblue @pzuraq @kellyselden I believe this is still an issue. It looks like what's happening is [raw](https://github.com/kellyselden/ember-macro-helpers/blob/master/addon/raw.js) returns the result of calling `Ember.computed()`, and [isComputed](https://github.com/kellyselden/ember-macro-helpers/blob/master/addon/is-computed.js) checks `instanceof Ember.ComputedProperty`, but `Ember.computed()` doesn't return an `Ember.ComputedProperty`, it returns one of [these](https://github.com/emberjs/ember.js/blob/91656e1154afe39791514cbe937ada954eab8d11/packages/%40ember/-internals/metal/lib/decorator.ts#L155-L193).

So I believe we need to fix the `isComputed()` check, but I'm not quite sure how -- I think [isClassicDecorator()](https://github.com/emberjs/ember.js/blob/91656e1154afe39791514cbe937ada954eab8d11/packages/%40ember/-internals/metal/lib/descriptor_map.ts#L45-L47) would do the job, but it's not public...

**Comment by bendemboski** [comment]
Oh, I just learned a little more. [Here](https://github.com/kellyselden/ember-macro-helpers/blob/0bc688055969b5b7751284352431a354b1c5caaf/addon/get-value.js#L6-L8) is the code that is doing the wrong thing, and as you can see, it's using the `_getter()` private API, but it never gets there because `isComputed()` always returns `false`.

**Comment by simonihmig** [comment]
> So I believe we need to fix the isComputed()

@bendemboski FYI, @pzuraq already submitted [this PR](https://github.com/kellyselden/ember-macro-helpers/pull/252) a while ago for the issue you described, but it still has some failing tests...

**Comment by simonihmig** [comment]
Btw, as much as I **love** being able to use the old CP functions straight away ss decorators, that change for `computed()` to not return a `ComputedProperty` instance anymore looks quite a bit like a SemVer breaking change AFAICT! As `computed()` has been documented as returning a `ComputedProperty` instance [here](https://api.emberjs.com/ember/3.8/functions/@ember%2Fobject/computed), and `ComputedProperty` is also documented as a public class, that `instanceof` check seems legit, so ideally under SemVer rules should not have been made to break!? 🤷‍♂️

**Comment by bendemboski** [comment]
I have what I think/hope is an acceptable fix in [this PR](https://github.com/kellyselden/ember-macro-helpers/pull/258), which moves `ember-macro-helpers` away from these private APIs
