### ISSUE TITLE
[Bug] Keypress and blur event handlers with a conditionally rendered element results in an exception

### ISSUE THREAD

**Issue by richard-viney** [emberjs/ember.js#19010]
I've run into an unexpected interaction with the use of both a blur and keypress event handler causing an auto tracking exception. It appears to be a regression in the Ember 3.17 release which persists into the current 3.19 release.

### 🔬 Minimal Reproduction

The following component conditionally renders an `<input>` element, and the input is hidden when enter is pressed or focus is lost:

```js
import { tracked } from "@glimmer/tracking"
import { action } from "@ember/object"
import Component from "@glimmer/component"

export default class InputWrapperComponent extends Component {
  @tracked isInputVisible = true

  // Tear down the <input> on pressing enter
  @action onKeyPress(event) {
    if (event.keyCode === 13) {
      this.isInputVisible = false
    }
  }

  // Tear down the <input> on blur
  @action onBlur() {
    this.isInputVisible = false
  }
}
```

```hbs
{{#if this.isInputVisible}}
  <input {{on "keypress" this.onKeyPress}} {{on "blur" this.onBlur}}>
{{/if}}
```

Then instantiate the component anywhere:

```hbs
<InputWrapper />
```

A GitHub repo demonstrating the issue is here: https://github.com/richard-viney/ember-blur-teardown-issue

### 😕 Actual Behavior
The code seems reasonable, however it result in an exception in `onBlur()` when enter is pressed:

```
Uncaught Error: Assertion Failed: You attempted to update `isInputVisible` on
`InputWrapperComponent`, but it had already been used previously in the
same computation.  Attempting to update a value after using it in a computation
can cause logical errors, infinite revalidation bugs, and performance issues, and
is not supported.

`isInputVisible` was first used:

- While rendering:
  
  application
    input-wrapper
      this.isInputVisible
```

This exception can be worked around by changing `onBlur()` to check the value before setting it:

```
  @action onBlur() {
    if (this.isInputVisible) {
      this.isInputVisible = false
    }
  }
```

### 🤔 Expected Behavior
No exception from the code as written. It works fine in Ember 3.16 (the current LTS). The issue described here first appeared in 3.17 and is still present in 3.19.

### 🌍 Environment

- Ember: 3.19
- Node.js/npm: 10.12
- OS: macOS 10.15
- Browser: Chrome 83

**Comment by rwjblue** [comment]
I believe that this is fixed in 3.20 (with the removal of the mandatory setter for `@tracked` contexts).

**Comment by richard-viney** [comment]
Unfortunately this still repros with `ember-source@3.20.0`.

Curiously, I just noticed that it repros in Chrome 83 but not in Safari 13.1.1 or Firefox 77.

This is because Firefox & Safari never actually call the `onBlur()` function, which can be observed by adding a `console.log()` to the top of `onKeyPress()` and `onBlur()`. Chrome however does call the `onBlur()` function, and therefore triggers the exception.

I don't currently have a good explanation for the difference between the browsers here.

**Comment by richard-viney** [comment]
Still present in Chrome in Ember 3.20.3.

This might be related to https://github.com/emberjs/ember.js/issues/18795, which is to do with modifier teardown. Perhaps this is subtly different between browsers.

**Comment by richard-viney** [comment]
Still present in Ember 3.24.1 and repros on Chrome 87.

**Comment by pzuraq** [comment]
I’m think this may actually be expected behavior. The input is triggering the `blur` event when the element is torn down, which is mid render. Blur events are synchronous by default. `isInputVisible` was just read to determine that the input should be torn down in the first place. So, it’s expected that this would trigger the assertion.

The main issue is why did this work at all prior to 3.17? I’m not sure which changes would have caused this behavior to change, except possibly some fixes to autotracking in general that happened at that time.

**Comment by richard-viney** [comment]
OK, and the difference in behavior between browsers is expected? This only affects Chrome as far as I can tell, so it might be an issue/bug in that browser.

**Comment by pzuraq** [comment]
Hmm, that is a bit odd. Does the event handler not trigger at all in Safari/Firefox? Or does it trigger later?

**Comment by richard-viney** [comment]
In Chrome, `onKeyPress` runs and then `onBlur` runs and results in the exception.

In both Safari and Firefox, only `onKeyPress` triggers. `onBlur` never runs and so there's no exception.

This issue in Chrome only seems to happen when the key involved is the Enter key. Changing it to the "a" key fixes the issue in Chrome. Perhaps Chrome is doing some specific handling for the Enter key that results in the blur event being triggered here, which the other browsers aren't doing.

**Comment by locks** [comment]
Closing as no longer relevant since the framework moved away from Ember Components to Glimmer components and the `{{on}}` modifier for event handling.
