### ISSUE TITLE
[Bug] New app CI tests broken

### ISSUE THREAD

**Issue by jtescher** [emberjs/ember.js#19425]
### 🐞 Describe the Bug

When creating new apps or upgrading existing ember applications to latest version, running tests with `CI=true` errors.

### 🔬 Minimal Reproduction

Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

```shell
$ ember new broken-ci-tests && cd broken-ci-tests
$ ember g component foo-bar
$ CI=true ember test
```

### 😕 Actual Behavior

Error output:

```
not ok 1 Chrome 88.0 - [2 ms] - TestLoader Failures: broken-ci-tests/tests/integration/components/foo-bar-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            Error: Could not find module `@ember/template-factory` imported from `broken-ci-tests/tests/integration/components/foo-bar-test`
                at missingModule (http://localhost:7357/assets/vendor.js:259:11)
                at findModule (http://localhost:7357/assets/vendor.js:270:7)
                at Module.findDeps (http://localhost:7357/assets/vendor.js:180:24)
                at findModule (http://localhost:7357/assets/vendor.js:274:11)
                at requireModule (http://localhost:7357/assets/vendor.js:36:15)
                at TestLoader.<anonymous> (http://localhost:7357/assets/test-support.js:7484:11)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:7474:27)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:7465:16)
                at loadTests (http://localhost:7357/assets/test-support.js:8123:22)
                at start (http://localhost:7357/assets/test-support.js:7863:33)
        message: >
            Died on test #1     at TestLoader.moduleLoadFailure (http://localhost:7357/assets/test-support.js:8096:15)
                at TestLoader.<anonymous> (http://localhost:7357/assets/test-support.js:7486:16)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:7474:27)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:7465:16)
                at loadTests (http://localhost:7357/assets/test-support.js:8123:22)
                at start (http://localhost:7357/assets/test-support.js:7863:33)
                at Module.callback (http://localhost:7357/assets/tests.js:71:25)
                at Module.exports (http://localhost:7357/assets/vendor.js:118:32): Could not find module `@ember/template-factory` imported from `broken-ci-tests/tests/integration/components/foo-bar-test`
        negative: >
            false
        browser log: |
    ...
ok 2 Chrome 88.0 - [0 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
not ok 3 Chrome 88.0 - [undefined ms] - Global error: Uncaught TypeError: Cannot read property 'length' of undefined at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 2332
 After execution of test: ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
    ---
        browser log: |
            testContext: [object Object]
            ERROR: Uncaught TypeError: Cannot read property 'length' of undefined at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 2332

    ...

```

### 🤔 Expected Behavior

Tests passing

### 🌍 Environment

- Ember: 3.25.1
- Node.js/npm:  v14.15.4 / 6.14.10
- OS: MacOS
- Browser: Chrome 88

**Comment by rwjblue** [comment]
Eeck! I think this was caused by recent changes in https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/338.

@pzuraq already landed an option to make the error go away (in https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/346) but we made it opt-in instead of the default value.

We need to update https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile to amke `options.ensureModuleApiPolyfill` true by default.

**Comment by rwjblue** [comment]
Sorry about this @jtescher, thanks for reporting!

**Comment by rwjblue** [comment]
The fix was released in https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/releases/tag/v4.4.2

**Comment by jtescher** [comment]
Thanks for the quick fix! great work everyone 🍻

**Comment by jamescdavis** [comment]
Looks like it didn't quite fix it. https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/349 should

**Comment by rwjblue** [comment]
Eeeck, thanks again @jamescdavis! 

https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/releases/tag/v4.4.4
