### ISSUE TITLE
[Documentation] `@ember/controller` and `Controller` are missing from 4.8 and 4.9 API docs

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#20348]
### 📙 Describe the Issue
The API documentation for `@ember/controller` is missing when version 4.8 or 4.9 is selected on https://api.emberjs.com

### 🔬 Minimal Reproduction
Visit https://api.emberjs.com/ember/release. Observe that `@ember/controller` is not listed under the "Packages" section, nor is `Controller` listed under "Classes".
Change the version to 4.7. Observe that `@ember/controller` is listed under "Packages" and `Controller` under "Classes".

### 😕 Actual Behavior
When the selected version is 4.8 or 4.9,`@ember/controller` is not listed under the "Packages" section, nor is `Controller` listed under "Classes".

### 🤔 Expected Behavior
`@ember/controller` is listed under "Packages" and `Controller` under "Classes".

### ➕ Additional Context
Attempting to edit the URL manually to change the version to 4.8 or 4.9 (e.g., https://api.emberjs.com/ember/4.9/modules/@ember%2Fcontroller) gives a 404 error.

**Comment by bertdeblock** [comment]
I think https://github.com/emberjs/ember.js/pull/20346 should fix the `@ember/controller` part.

**Comment by johanrd** [comment]
@bertdeblock still reproducible for the range [4.8](https://api.emberjs.com/ember/4.8)–[4.11](https://api.emberjs.com/ember/4.11) it seems:

<img width="381" height="156" alt="Image" src="https://github.com/user-attachments/assets/fac6609a-6f6d-4f84-a8d6-53e8a6ac7991" />


see https://github.com/emberjs/ember.js/pull/21106 for a bacport to LTS 4.8 (at least)
